BullshitTracker/BullshitTracker/Controllers/BudgetVsActualController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BullshitTracker.Models;

namespace BullshitTracker.Controllers
{
    [Authorize(Roles = @"Planner")]
    public class BudgetVsActualController : Controller
    {
        private BullshitTrackerEntities db = new BullshitTrackerEntities();

        // GET: /BudgetVsActual/
        public ActionResult Index(int? periodId)
        {


            if (periodId == null)
            {

                periodId = db.Periods.Where(n => n.EndDate >= DateTime.Now && n.StartDate <= DateTime.Now).SingleOrDefault().Id;
            };

            ViewBag.PeriodName = db.Periods.Find(periodId).Name.ToString();

            ViewBag.Previous = periodId - 1;
            ViewBag.Next = periodId + 1;

            ViewBag.PeriodTotalActual = String.Format("{0:###,##0.00}",db.PeriodBudgetVsActualSummaries.Where(n => n.PeriodId == periodId).SingleOrDefault().ActualAmount);
            ViewBag.PeriodBudgeted = String.Format("{0:###,##0.00}", db.PeriodBudgetVsActualSummaries.Where(n => n.PeriodId == periodId).SingleOrDefault().BudgetedAmount);
            ViewBag.PercentOfBudget = string.Format("{0:0}", db.PeriodBudgetVsActualSummaries.Where(n => n.PeriodId == periodId).SingleOrDefault().PercentOfBudget);


            return View(db.PeriodBudgetVsActuals.ToList().Where(n => n.PeriodId == periodId));


        }

        // GET: /BudgetVsActual/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeriodBudgetVsActual periodbudgetvsactual = db.PeriodBudgetVsActuals.Find(id);
            if (periodbudgetvsactual == null)
            {
                return HttpNotFound();
            }
            return View(periodbudgetvsactual);
        }

        // GET: /BudgetVsActual/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /BudgetVsActual/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,PeriodId,PeriodName,StartDate,EndDate,BudgetId,BudgetName,ActualAmount,BudgetedAmount,PercentOfBudget,Month,Year")] PeriodBudgetVsActual periodbudgetvsactual)
        {
            if (ModelState.IsValid)
            {
                db.PeriodBudgetVsActuals.Add(periodbudgetvsactual);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(periodbudgetvsactual);
        }

        // GET: /BudgetVsActual/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeriodBudgetVsActual periodbudgetvsactual = db.PeriodBudgetVsActuals.Find(id);
            if (periodbudgetvsactual == null)
            {
                return HttpNotFound();
            }
            return View(periodbudgetvsactual);
        }

        // POST: /BudgetVsActual/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,PeriodId,PeriodName,StartDate,EndDate,BudgetId,BudgetName,ActualAmount,BudgetedAmount,PercentOfBudget,Month,Year")] PeriodBudgetVsActual periodbudgetvsactual)
        {
            if (ModelState.IsValid)
            {
                db.Entry(periodbudgetvsactual).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(periodbudgetvsactual);
        }

        // GET: /BudgetVsActual/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PeriodBudgetVsActual periodbudgetvsactual = db.PeriodBudgetVsActuals.Find(id);
            if (periodbudgetvsactual == null)
            {
                return HttpNotFound();
            }
            return View(periodbudgetvsactual);
        }

        // POST: /BudgetVsActual/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PeriodBudgetVsActual periodbudgetvsactual = db.PeriodBudgetVsActuals.Find(id);
            db.PeriodBudgetVsActuals.Remove(periodbudgetvsactual);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BullshitTracker/BullshitTracker/Views/BudgetVsActual/Create.cshtml
@model BullshitTracker.Models.PeriodBudgetVsActual

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PeriodBudgetVsActual</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id)
                @Html.ValidationMessageFor(model => model.Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PeriodId)
                @Html.ValidationMessageFor(model => model.PeriodId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PeriodName)
                @Html.ValidationMessageFor(model => model.PeriodName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BudgetId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudgetId)
                @Html.ValidationMessageFor(model => model.BudgetId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BudgetName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudgetName)
                @Html.ValidationMessageFor(model => model.BudgetName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActualAmount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActualAmount)
                @Html.ValidationMessageFor(model => model.ActualAmount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BudgetedAmount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudgetedAmount)
                @Html.ValidationMessageFor(model => model.BudgetedAmount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PercentOfBudget, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PercentOfBudget)
                @Html.ValidationMessageFor(model => model.PercentOfBudget)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month)
                @Html.ValidationMessageFor(model => model.Month)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BullshitTracker/BullshitTracker/Views/BudgetVsActual/Delete.cshtml
@model BullshitTracker.Models.PeriodBudgetVsActual

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PeriodBudgetVsActual</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PeriodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BudgetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BudgetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BudgetedAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BudgetedAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PercentOfBudget)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PercentOfBudget)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BullshitTracker/BullshitTracker/Views/BudgetVsActual/Details.cshtml
@model BullshitTracker.Models.PeriodBudgetVsActual

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PeriodBudgetVsActual</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PeriodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BudgetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BudgetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BudgetedAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BudgetedAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PercentOfBudget)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PercentOfBudget)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BullshitTracker/BullshitTracker/Views/BudgetVsActual/Edit.cshtml
@model BullshitTracker.Models.PeriodBudgetVsActual

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PeriodBudgetVsActual</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        @Html.HiddenFor(model => model.PeriodId)

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PeriodName)
                @Html.ValidationMessageFor(model => model.PeriodName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>

        @Html.HiddenFor(model => model.BudgetId)

        <div class="form-group">
            @Html.LabelFor(model => model.BudgetName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudgetName)
                @Html.ValidationMessageFor(model => model.BudgetName)
            </div>
        </div>

        @Html.HiddenFor(model => model.ActualAmount)

        <div class="form-group">
            @Html.LabelFor(model => model.BudgetedAmount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BudgetedAmount)
                @Html.ValidationMessageFor(model => model.BudgetedAmount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PercentOfBudget, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PercentOfBudget)
                @Html.ValidationMessageFor(model => model.PercentOfBudget)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month)
                @Html.ValidationMessageFor(model => model.Month)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BullshitTracker/BullshitTracker/Views/BudgetVsActual/Index.cshtml
@model IEnumerable<BullshitTracker.Models.PeriodBudgetVsActual>

@{
    ViewBag.Title = "Index";
}

<h2>Budget vs Actual for @ViewBag.PeriodName</h2>

@Html.ActionLink("←Previous", "Index", "BudgetVsActual", new { periodId = @ViewBag.Previous }, new { @class = "btn btn-default btn-large" })
@Html.ActionLink("Next→", "Index", "BudgetVsActual", new { periodId = @ViewBag.Next }, new { @class = "btn btn-default btn-large" })

<br />
<br />

<table class="table">
    <colgroup>
        <col width="80" />
        <col width="200" />
        <col width="100" />
        <col width="100" />
        <col width="100" />

    </colgroup>
    <tr style="font-size:larger">

        <th colspan="2">
            Budget
        </th>

        <th style="text-align:right">
            Budget Amt.
        </th>
        <th style="text-align:right">
            Actual Amt.
        </th>
        <th style="text-align:right">
            % of Budget
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr style="background-color:azure; font-size:larger">

            <td colspan="2">

                    @Html.ActionLink(item.BudgetName, "Index", "ExpenseDetails", new { Budget = item.BudgetId, Period = item.PeriodId }, null)


            </td>
            
            <td style="text-align:right">

  
            </td>
            <td style="text-align:right; font-weight:bold">

     
            </td>
            <td style="text-align:right">

            </td>

        </tr>


        foreach (var item2 in item.PeriodCategoryTotals) {
            <tr>
                <td></td>
                
                <td>
                    @Html.ActionLink(item2.CategoryName, "Index", "ExpenseDetails", new { Budget = item2.BudgetId, Period = item2.PeriodId, Category = item2.CategoryId }, null)
 </td>    
                
                <td style="text-align:right">@Html.DisplayFor(modelItem => item2.BudgetAmount)</td>

                <td style="text-align:right">
                    @Html.DisplayFor(modelItem => item2.ActualAmount)


                    </td>
                <td style="text-align:right">
                    @Html.DisplayFor(modelitem=>item2.PercentOfBudget)%
                </td>
                </tr>

                    }


                    }

            <tr style="font-weight:bold; font-size:larger">
                <td>
                    Total
                </td>
                <td></td>
                <td style="text-align:right">

                
                </td>
                <td style="text-align:right; font-weight:bold">


                </td>
                <td style="text-align:right">

                </td>

            </tr>

        </table>